project:
  type: website
  output-dir: docs
  resources:
    - .well-known
    - assets
    - robots.txt
  preview:
    port: 3000

website:
  title: "KeishiS.github.io"
  site-url: https://www.keishis.xyz
  description: "Vitae website for KeishiS, including some technology articles"
  navbar:
    right:
      - text: "Posts"
        href: posts.qmd
      - icon: github
        href: https://github.com/KeishiS/keishis.github.io
      - icon: rss
        href: index.xml
format:
  html:
    theme: lux
    css: styles.css



