site:
  title: KeishiS HOME
  url: https://KeishiS.github.io
  start_page: docs::index.adoc
content:
  sources:
    - url: .
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
output:
  dir: public
