= Machine Setup
:github-url: https://github.com/KeishiS

== Machineの主要構成

以降の記述に従えば，自分と（ほぼ）同じ環境を構築できる．

Disk encryption: link:https://wiki.archlinux.jp/index.php/Dm-crypt/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E5%85%A8%E4%BD%93%E3%81%AE%E6%9A%97%E5%8F%B7%E5%8C%96[LUKS on LVM]::
    暗号化の方法の1つとしてこちらを採用している．後述の構築方法ではswap領域は暗号化できていない点に留意．復号化はパスワードを入力するのではなく，USBメモリに入れた復号化キーを使用する設定を採用．
OS: link:https://archcraft.io/[Archcraft]::
    ArchLinux系distroのうち，柔軟なインストール方法を提供しているものとして採用．USBメモリに格納したluksキーを用いて復号化するLUKS on LVM構成を実現するのに，Calamares installerを採用しているdistroは不便という理由もある．
window manager: link:https://i3wm.org/[i3wm]::
    タイル型が好きという理由で採用．swayも興味あるがwaylandとfcitx-mozcの設定がうまくできなかったためまだ避けている．
terminal: link:https://wezfurlong.org/wezterm/[WezTerm]::
    日本語入力できて，fallback fontが設定できて，ligature fontも使えて，細かいところにも手が届く有能ターミナルエミュレータ

== 事前情報 : ディスク構成

ディスク名は読み込み順等で変動するため，個々の環境に応じて読み換えていただくとして，以降では便宜上，下記の通り記述する．

`/dev/sda`::
    OSをインストールする物理ディスクの1つ．UEFIブートのための領域もここに確保する．
`/dev/sdb`::
    OSをインストールする物理ディスクその2．こちらはLVM領域のみで構成する．
`/dev/sdc`::
    USBメモリで，ここに鍵を入れておく想定．
`/dev/sdd`::
    ArchcraftのISOが入っているUSBメモリ

== 復号化キーの準備

USBメモリを初期化して鍵を作成する．

[source,shell]
--
# ファイルシステムの作成
mkfs.vfat -F 32 -n KEYCASE /dev/sdc

# 鍵の作成: 長さはお好みで
dd if=/dev/urandom of=./keyfile bs=1 count=2048

# 保存
mount /dev/disk/by-label/KEYCASE /mnt
cp ./keyfile /mnt/keyfile
umount /mnt
--

== パーティションの準備

下記のようなパーティション構成になるよう， `gdisk` 等でテーブルを作成する．

[source,shell]
--
> gdisk -l /dev/sda
Number  Start (sector)    End (sector)  Size       Code  Name
   1            xxxx         xxxxxxx   xxxx.x MiB  EF00  EFI system partition
   2         xxxxxxx      xxxxxxxxxx   xxx.x GiB   8E00  Linux LVM

> gdisk -l /dev/sdb
Number  Start (sector)    End (sector)  Size       Code  Name
   1            xxxx       xxxxxxxxx   xxx.x GiB   8E00  Linux LVM
--

LVMで論理ボリュームを作成していく．このあたりは好みだが，自分の場合は細かく分ける利点がないため，以降ではswap領域とroot領域の2つのみを作成している．

[source,shell]
--
# 物理ボリュームの作成
pvcreate /dev/sda2 /dev/sdb1

# ボリュームグループの作成
vgcreate archcraft /dev/sda2 /dev/sdb1

# 論理ボリュームの作成
lvcreate --name swap -L xxGB archcraft
lvcreate --name root -l 100%FREE archcraft

# LUKSによる暗号化
mkdir ./mnt
mount /dev/disk/by-label/KEYCASE ./mnt
cryptsetup luksFormat --key-file ./mnt/keyfile /dev/mapper/archcraft-root

# ファイルシステムの作成
mkfs.vfat -F 32 /dev/sda1
mkswap /dev/mapper/archcraft-swap

cryptsetup open --key-file ./mnt/keyfile /dev/mapper/archcraft-root unlocked
mkfs.ext4 /dev/mapper/unlocked
--

== OSのインストール

上記の作業をUSBブートしたArchcraft上でも，別のLinux環境下で実施しても問題ない．
以降の作業はUSBブートしたArchcraftであることを想定する．

. `Archcraft installer (CLI)` の実行: 案内に沿って選択していくだけだが，ここではブートマネージャに `systemd-boot` を採用
. installer 終了後，terminal を開いて xref:after-install-os[後述の作業]を実施

[source,shell]
.<<after-install-os, OSインストール後の作業>>
--
> mount /dev/mapper/unlocked /mnt
> mount /dev/sda1 /mnt/boot
> arch-chroot /mnt
>> nano /etc/mkinitcpio.conf
# MODULES に vfat を追記
# HOOKS に encrypt を追記
>> mkinitcpio -p linux
>> nano /boot/loader/entries/archcraft.conf
# options に cryptkey=/dev/disk/by-label/KEYCASE:vfat:/keyfile を追記
>> echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
# ビープ音の無効化
>> nano /etc/systemd/sleep.conf
# ハイブリッドスリープの設定
--

以上でOSのセットアップは完了．

== 作業環境の整備

残っている細々した設定を行う．なるべくコマンド実行で完結するようにしているが，一部GUIでの操作が必要な箇所がある．

. 作業ユーザでログイン
. `git clone {github-url}/dotfiles.git ~/dotfiles`
. `sudo pacman -S - < ~/dotfiles/pacman.list`
. `yay -S - < ~/dotfiles/yay.list`
. `source ~/dotfiles/setup.sh`
. 一旦再起動
. [GUI操作] fcitx5-mozcの設定を実施

以上で一通りの作業が完了．

== おまけ：外付けWindowsの設定

基本的な研究活動はLinux distroで完結しますが，大学の書類等がofficeソフトを強要してくるため，遺憾ながら編集環境を整備する必要があります．web版Microsoft 365を使う手段もありますが，たまにレイアウトが崩れたりする場面に遭遇すると安心はできません．

一方で，同一ディスク上でのデュアルブートは，予期しないブートローダの挙動を招いた経験上したくありません．以上の理由から，外付けディスクへWindowsをインストールし，必要な時だけ接続して使うという運用を採用しました．

以降のインストールは，ライセンス認証上問題ないことを各自の環境で確認の上，参考にしてください．また以降の内容は link:https://blue1st.hateblo.jp/entry/2018/02/18/061620[先駆者の記事]の内容をそのまま採用している事をご承知おきください．

必要なもの::
    * 上記でLinuxをインストールしたPC
    * Windowsのインストール先となる外付けHDD / SSD
    * WindowsのインストールメディアとなるUSBフラッシュディスク：割当ドライブを `D` とする
手順::
    . 外付け記憶媒体へWindowsのインストール：適当なWindows端末で下記を実行
    .. Windowsのインストールメディア作成：Microsoft公式ページからツールをダウンロードして実施
    .. 外付け記憶媒体のパーティション作成：WindowsのPowerShellを管理者権限で xref:creating-windows-partition[下記コマンド] を実行
    .. インストールメディア内の該当OSの割当場所確認： `dism /get-imageinfo /imageFile:D:\sources\install.esd` でインデックスを確認．ここでは `2` と仮定
    .. Windowsを外付け記憶媒体へ展開： `dism /apply-image /imageFile:D:\sources\install.esd /index:2 /applydir:I:\`
    .. ブートセクタの作成： `bcdboot i:\Windows /l ja-jp /s s: /f UEFI`
    . 再起動 & 外付け記憶媒体から起動し，初期設定を実行

[source,shell]
.<<creating-windows-partition,Windowsのパーティション作成>>
--
> diskpart
# ディスクのフォーマット
> clean

# パーティション形式の指定
> convert gpt

# EFI領域の作成 & 初期化 & Sドライブの割当
> create partition efi size=1024
> format fs=fat32 quick label="EFI"
> assign letter=S

# ルート相当の領域作成 & 初期化 & Iドライブの割当
> create partition primary
> format fs=ntfs quick label="Windows"
> assign letter=I

# 終了
> exit
--

=== ハードウェアクロックをUTCへ変更

LinuxとWindowsのデュアルブートでおかしくなる事の1つに時刻表示があります．これはハードウェアクロックの管理方法がOSで異なることに起因します．一般にLinuxではUTCを用いるのに対し，Windowsではローカルタイムを採用します．ここではLinuxに合わせるよう，Windows側を修正します．

以降の内容は link:https://hattomo.github.io/posts/main/21/q1/0213-mangae-hardware-clock-windows-utc/[こちらの方の記事]の方法を採用しています．

[source,shell]
--
# LocalTime -> UTC のために，管理者権限のコマンドプロンプトで下記を実行
reg add HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation /v RealTimeIsUniversal /d 1 -t REG_DWORD /f

# UTC -> LocalTime に戻す場合は下記を実行
reg delete HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation /v RealTimeIsUniversal /f
--