on:
    workflow_dispatch:
    push:
        branches: main

name: Quarto Publish
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Quarto
              uses: quarto-dev/quarto-actions/setup@v2
            - name: Setup Julia
              uses: julia-actions/setup-julia@v2
            - run: julia -e 'println("Hello, World!")'
