on:
    workflow_dispatch:
    push:
        branches: main

permissions:
    contents: read
    pages: write
    id-token: write

name: Quarto Publish
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Quarto
              uses: quarto-dev/quarto-actions/setup@v2
              with:
                version: 1.4.515
            - run: quarto --version
            - name: Setup Julia
              uses: julia-actions/setup-julia@v2
            - name: Render Quarto Project
              uses: quarto-dev/quarto-actions/render@v2
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3.0.1
              with:
                path: docs
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: setup
        runs-on: ubuntu-latest
        name: Deploy to Pages
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
